Добавить продолжительность, время начала задач
jesusdangerous/java-kanban pull request #3
Opened 2024-10-21 11:03 UTC by jesusdangerous

Сделать проверку на пересечение интервалов, написать логику вывода задач в порядке приоритета, создать абстрактный класс для тестов

2024-10-21 16:22 UTC, NikolaiDem requested changes
Нужны тесты, проверяющие обновление временных параметров тасок и сабтасок.
А так же тесты, проверяющие консистентность тасок с приоритетным списком при добавлении, удалении и обновлении тасок

2024-10-22 06:08 UTC, NikolaiDem commented on test/TaskManagerTest.java
> +    void shouldConsistencyTasks() {
Большие тесты плохо читаются. Лучше разделить так, чтобы проверки стали атомарными

2024-10-22 06:08 UTC, NikolaiDem commented on test/TaskManagerTest.java
> +    }
Почему не работает тест?

    @Test
    void shouldConsistencyTasks() {
        LocalDateTime startTime = LocalDateTime.of(2024, 10, 22, 10, 0);
        Duration oneMinute = Duration.ofHours(1);
        Task task = new Task("Задача1", "Описание1", Status.NEW, startTime, oneMinute);
        Task collisionTask = new Task("Задача2", "Описание2", Status.NEW, startTime.plus(oneMinute), oneMinute);

        taskManager.addNewTask(task);
        taskManager.addNewTask(collisionTask);
        Task taskToUpdate = new Task("Задача1", "Описание1", Status.NEW, startTime.plus(oneMinute), oneMinute);
        taskToUpdate.setId(task.getId());
        taskManager.updateTask(taskToUpdate);

        Assertions.assertEquals(List.of(task, collisionTask), taskManager.getPrioritizedTasks());
    }

2024-10-22 08:24 UTC, jesusdangerous commented on test/TaskManagerTest.java
> +    }
Добрый день! Немного не понял, а разве у нас не будет одинаковое время у этих задач, и поэтому task не добавится в TreeSet?

2024-10-22 09:27 UTC, NikolaiDem commented on test/TaskManagerTest.java
> +    }
Добрый день!
До обновления в менеджере должно быть 2 задачи.
Потом делаем обновление, но оно будет не успешным, поэтому в менеджере так и должно остаться 2 этих задачи

2024-10-22 20:24 UTC, NikolaiDem requested changes

2024-10-22 20:24 UTC, NikolaiDem commented on src/project/manager/InMemoryTaskManager.java
> +            addTaskInPrioritizedTasks(task);
Нужно добавить тест на консистентность мапы тасок и сета приоритетных тасок. Нужно, чтобы задаче в мапе всегда соответствовала задача в сете (при условии наличия времени в ней)

2024-10-22 20:24 UTC, NikolaiDem commented on src/project/manager/InMemoryTaskManager.java
> +                if (isTaskIntersection(subtask)) {
Зачем дважды проверять пересечение и делать удаление?

2024-10-22 20:24 UTC, NikolaiDem commented on src/project/manager/InMemoryTaskManager.java
>          if (subtask != null) {
Обновление для сабтаски может выглядеть так:

    @Override
    public void updateSubtask(Subtask subtask) {
        Objects.requireNonNull(subtask, "Subtask for update must not be null");
        var subtaskId = subtask.getId();
        if (!subtasks.containsKey(subtaskId)) {
            throw new IllegalArgumentException("No subtask by id %s".formatted(subtaskId));
        }
        var epicId = subtask.getEpicId();
        if (!epics.containsKey(epicId)) {
            throw new IllegalArgumentException("No epic by id %s".formatted(subtaskId));
        }
        var epic = epics.get(epicId);
        if (!epic.getSubtasks().contains(subtaskId)) {
            throw new IllegalArgumentException("Subtask with id=%s is not related to epic with id=%s".formatted(subtaskId, epicId));
        }
        var oldSubtask = subtasks.get(subtaskId);
        prioritizedTasks.remove(oldSubtask);
        if (hasIntersections(subtask)) {
            prioritizedTasks.add(oldSubtask);
            throw new IllegalArgumentException("Subtask with id=%s has intersection".formatted(subtaskId));
        }
        subtasks.put(subtaskId, subtask);
        prioritizedTasks.add(subtask);
        updateEpicStatus(epic);
        updateEpicTime(epic);
    }

    private boolean hasIntersections(Task newTask) {
        return prioritizedTasks.stream()
                .anyMatch(task -> hasIntersection(newTask, task));
    }

    private boolean hasIntersection(Task task1, Task task2) {
        return task1.getStartTime().isBefore(task2.getEndTime()) && task1.getEndTime().isAfter(task2.getStartTime());
    }

Исправить и для обновления таски

2024-10-23 07:36 UTC, jesusdangerous commented on src/project/manager/InMemoryTaskManager.java
>          if (subtask != null) {
Если удалять таску как объект из приоритетных задач, то не всегда будет гарантированно удаление? Лучше удалять по id?

2024-10-23 18:42 UTC, NikolaiDem approved these changes

2024-10-25 13:15 UTC, merged