Реализовать работу HttpServer, написать обработчики http-запросов, написать для каждого запроса тест
jesusdangerous/java-kanban pull request #4
Opened 2024-11-05 11:17 UTC by jesusdangerous

2024-11-06 12:34 UTC, NikolaiDem requested changes

2024-11-06 12:34 UTC, NikolaiDem commented on src/project/manager/handlers/BaseHttpHandler.java
> +        byte[] resp = text.getBytes(StandardCharsets.UTF_8);
Лучше использовать try with resources, чтобы закрыть соединение в случае ошибки
        try (exchange) {
            byte[] resp = text.getBytes(StandardCharsets.UTF_8);
            exchange.getResponseHeaders().add("Content-Type", "application/json;charset=utf-8");
            exchange.sendResponseHeaders(200, resp.length);
            exchange.getResponseBody().write(resp);
        }
Аналогично для остальных обработчиков

2024-11-06 12:34 UTC, NikolaiDem commented on src/project/manager/handlers/BaseHttpHandler.java
> +                        if (splitStrings.length == 3) {
Отличия в эндпоинтах создания и обновления в id тела запроса, а не пути.
Аналогично для эпиков и сабтасок

2024-11-06 12:34 UTC, NikolaiDem commented on src/project/manager/handlers/EpicHandler.java
> +                taskManager.updateEpic(epic);
Лучше вместо вызова taskManager.getEpicById(epic.getId()) бросать ошибку в updateEpic(...), если передан некорректный объект для обновления.
Аналогично для метода удаления, тасок и сабтасок

2024-11-06 12:34 UTC, NikolaiDem commented on src/project/manager/handlers/EpicHandler.java
> +        } catch (IllegalArgumentException e) {
В эпике нет пересечений

2024-11-09 11:28 UTC, jesusdangerous commented on src/project/manager/handlers/BaseHttpHandler.java
> +                        if (splitStrings.length == 3) {
Добрый день! Немного не понял, как лучше изменить проверку

2024-11-09 22:42 UTC, NikolaiDem commented on src/project/manager/handlers/BaseHttpHandler.java
> +                        if (splitStrings.length == 3) {
Добрый день!
Запрос на обновление должен быть таким:
HttpRequest.newBuilder()
                .uri(URI.create(URL + "/tasks"))
                .header("Content-Type", "application/json")
                .POST(HttpRequest.BodyPublishers.ofString(taskToJson2))
                .build();
id передается в теле запроса

2024-11-10 17:45 UTC, NikolaiDem approved these changes

2024-11-11 05:29 UTC, merged